### ISSUE TITLE
Bug in implementing SKAdNetwork in unreal engine 4.27 , Info.plist Generator bug

### ISSUE THREAD

**Issue by awsproserve** [AppLovin/AppLovin-MAX-Unreal#12]
### MAX Plugin Version

 1.1.2

### Unreal Engine Version

4.27

### Device/Platform Info

IOS, Android

### Current Behavior

Issue 1: when I go to the following site I am suppose to click the check boxes (to generate Implement SKAdNetwork code) which should generate the code I need to add to my application, however all the code is showing up, its not filtering by the checkboxes I select. see attached screenshot.
https://dash.applovin.com/documentation/mediation/unreal/getting-started/skadnetwork-info

Issue 2: Im not seeing anywhere in the documentation to implement any of the ad types, (ie banner, interstitial etc) via blueprint, is it possible to do this via blueprint vs c++ code for unreal engine. and if it is not currenlty possible is it currently on the roadmap, as our game studios leverages blueprints only. Many thanks. 

![bug](https://user-images.githubusercontent.com/116039531/201499640-203881cf-569c-4844-9059-399a08dc1d87.png)

### Expected Behavior

issue 1: when I click the check boxes to implement SKAdNetwork, the page will only render the SkAdnetworks I choose from the checkboxes, right now its choosing all of them. 

issue 2: any blueprint documentation on the site? not seeing any.

### How to Reproduce

For issue 1:
1. go to https://dash.applovin.com/documentation/mediation/unreal/getting-started/skadnetwork-info
2. click the checkbox for the add networks you are using
3. then the list below should only show the ad networks you checked in the checkboxes above.

For issue 2: Blueprint instructions should be included on git or on the documentation page for unreal engine.

Many thanks :)

### Additional Info

na

**Comment by thomasmso** [comment]
Hi, for issue 1, I just checked that the code snippet is behaving correctly. By default, AppLovin serves ads from many advertisers that have their own SKAdNetwork IDs which is why you see the large list.

For issue 2, I will let my colleague @ritamsarmah help answer.

**Comment by ritamsarmah** [comment]
Hi @awsproserve, although we don't have blueprint docs yet, we currently do support using them to configure our plugin and implement all ad formats.

You may refer to the [header file here](https://github.com/AppLovin/AppLovin-MAX-Unreal/blob/master/AppLovinMAXDemo/Plugins/AppLovinMAX/Source/AppLovinMAX/Public/AppLovinMAX.h) to identify the functions exposed to blueprints, based on whether they are annotated as `BlueprintCallable`. Since our docs are based on the equivalent C++ functions, you can still refer to them for your integration. The only limitation for blueprints is that they do not support using delegate callbacks at the moment (e.g., `FOnInterstitialLoadedDelegate`).

**Comment by awsproserve** [comment]
Sounds great thank you. We’ll try using blueprint. Also does your plugin support unreal engine version 5.xx

Sent from my iPhone

On Nov 13, 2022, at 12:38 PM, Ritam Sarmah ***@***.***> wrote:

﻿

Hi @awsproserve<https://github.com/awsproserve>, although we don't have blueprint docs yet, we currently do support using them to configure our plugin and implement all ad formats.

You may refer to the header file here<https://github.com/AppLovin/AppLovin-MAX-Unreal/blob/master/AppLovinMAXDemo/Plugins/AppLovinMAX/Source/AppLovinMAX/Public/AppLovinMAX.h> to identify the functions exposed to blueprints, based on whether they are annotated as BlueprintCallable. Since our docs are based on the equivalent C++ functions, you can still refer to them for your integration. The only limitation for blueprints is that they do not support using delegate callbacks at the moment (e.g., FOnInterstitialLoadedDelegate).

**Comment by ritamsarmah** [comment]
Yep, we do support Unreal Engine 5
