### ISSUE TITLE
Poor documentation

### ISSUE THREAD

**Issue by NursultanNazarov** [AppLovin/AppLovin-MAX-Unreal#17]
Why documentation is so poor? You are a billion-dollar company, right?
Your official documentation is so confusing that I barely was able to show ads. But that's without all the setup for GDPR and God knows what other things I have to set up. Probably will take weeks to figure this out. Can't set up mediation for hours now. Other companies' plugin much easier to implement. Only reason to use applovin sdk was Yandex ads. I mean that's ONLY reason. 

Shame on you Applovin.

**Comment by NursultanNazarov** [comment]
> Thanks for raising your concern - how would you suggest we improve our documentation?

https://github.com/Flakky/unreal-applovin Look at this unofficial applovin plugin. So clear what to do to implement. Put your Applovin SDK key then other networks app id. In applovin's off plugin there's nothing about where to put SDK key(It's in Constant.cpp or .h file I don't remember for those who is looking). Make a make a video tutorial maybe. There's ZERO written or video tutorial on the whole internet. It made me feel you guys really don't care about Unreal Engine developers, only Unity or app developers

**Comment by thomasmso** [comment]
We'll discuss internally on what we could improve on and report back. In the meantime, if there are more examples you believe we can improve on, please let us know. Also, the Unreal plugin is relatively new compared to our Unity plugin, but we appreciate the feedback.

**Comment by ritamsarmah** [comment]
Hi @NursultanNazarov, we've updated our docs and README with some much better instructions for initializing the plugin and SDK key. If you have any specific further suggestions for documentation improvements or other questions regarding the plugin, feel free to let us know.
