### ISSUE TITLE
Offerwalls

### ISSUE THREAD

**Issue by MamatKunem** [AppLovin/AppLovin-MAX-Unreal#38]
### Feature Description

Hi, I would really like to see support for Offerwalls, why haven’t they been added? As I understand it, Aplovin Max supports them
https://www.applovin.com/glossary/offerwall-ads/

**Comment by thomasmso** [comment]
Hi @MamatKunem, we do not support Offer Walls, nor have any plans to. If we ever do, you will receive a product email from us.
