### ISSUE TITLE
Generating universal APK from bundle problem

### ISSUE THREAD

**Issue by NikitaAksenov** [AppLovin/AppLovin-MAX-Unreal#9]
### MAX Plugin Version

1.1.1

### Unreal Engine Version

4.27

### Device/Platform Info

Android

### Current Behavior

I've faced a problem when trying to build my project for Android using Max plugin.

In Project settings "Generate Bundle" is set to true, but after building my package I get two .aab files: "_-arm64.aab" and "_-armv7.aab".

But without plugin after building we got one .aab file.

### Expected Behavior

I've expected that with "Generate Bundle" is set to true I'll get one .aab file.

### How to Reproduce

Build project on Unreal Engine 4.27 for Android with AppLovin's MAX plugin with "Generate Bundle" set to true.

**Comment by vtzay** [comment]
I also cath this problem. Unreal exports 2 aab and 2 apk files, even if option split ABI sets to false.

**Comment by ritamsarmah** [comment]
Hi @NikitaAksenov, @vtzay

I wasn't able to replicate the problem in our demo project. Could you verify which architectures are enabled in your project under Project Settings > Platforms > Android > Build? If you have both armv7 and arm64 checked, I'd expect you'd get separate builds for each.

These were the settings I had checked, for example:

<img width="296" alt="Screen Shot 2022-10-28 at 12 54 52 PM" src="https://user-images.githubusercontent.com/17148467/198721365-e9ba9655-05ef-4f46-afa9-c649f65ebd04.png">

**Comment by NikitaAksenov** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/17599982/198949675-cde49ffa-2eaf-49af-a833-3cbab266ab50.png)

**Comment by ritamsarmah** [comment]
Hi, a fix for this issue has been included in the latest plugin release, 1.1.2.
